# Instagram Configuration
instagram:
  page-id: ${INSTAGRAM_PAGE_ID}
  webhook:
    verify-token: ${INSTAGRAM_VERIFY_TOKEN} # .env faylidan olinadi
  api:
    messenger:
      access-token: ${INSTAGRAM_MESSENGER_ACCESS_TOKEN} # .env faylidan olinadi
  business:
    username: "muhammadjonsaidov76"

# Spring Boot Configuration
spring:
  # Database Connection
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA & Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Connection
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2000ms

  # Email Sender Configuration
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000   # 15 daqiqa
  refresh-token-expiration: 86400000 # 24 soat

# SpringDoc (Swagger) Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method